version: '3.8'

services:
  app:
    build: .
    container_name: rental_kendaraan_app
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER} # Akan diambil dari .env atau environment variable
      DB_PASSWORD: ${DB_PASSWORD} # Akan diambil dari .env atau environment variable
      DB_NAME: ${DB_NAME} # Akan diambil dari .env atau environment variable
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: rental_kendaraan_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Gunakan password kuat
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      # Jika Anda memiliki dump SQL awal, Anda bisa menambahkannya di sini
      - ./rental_kendaraan.sql:/docker-entrypoint-initdb.d/rental_kendaraan.sql

volumes:
  db_data: