version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # GANTI 'YOUR_DOCKER_USERNAME_HERE' DENGAN USERNAME DOCKER HUB ANDA YANG SEBENARNYA
    image: mnaufalfs/rental_kendaraan_new:latest
    restart: always
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD_DOCKER }}
      DB_NAME: rental_kendaraan
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD_DOCKER }}
      MYSQL_DATABASE: rental_kendaraan
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: